version: '3'

vars:
  BUILD_TIME:
    sh: date -u '+%Y-%m-%d %I:%M:%S %Z'
  BUILD_COMMIT:
    sh: git rev-parse HEAD

tasks:
  run:
    desc: Build binary & Run
    deps: [ build ]
    cmds:
      - ./.bin/EggMD web
    sources:
      - eggmd.go
      - internal/**/*.go

  build:
    desc: Build binary
    cmds:
      - go build -v
        -trimpath
        -o ./.bin/EggMD